#!/bin/bash
set -e

(
  mkdir -p dist && cd dist
  curl -fLO https://files.pythonhosted.org/packages/4b/89/07f2f6c01ab2a87941f4e01562388d720572370a0584cb9b5af63bccfaf9/yapic.json-1.3.0.tar.gz
)
docker run --rm \
  -v $(pwd)/dist:/dist \
  -e PLAT_PYVER=3.6 \
  --entrypoint bash \
  ${IMAGE_NAME} build-wheel-from-sdist
